FORMAT: 1A

# fullStack - new 
##Allowed HTTPs requests:

- `POST` - Creates or updates a resource
- `PUT` - Updates a resource
- `GET` - Retrieves a resource or list of resources
- `DELETE` - Delete a resource

##Typical Server Responses

- 200 `OK` - The request was successful (some API calls may return 201 instead).
- 201 `Created` - The request was successful and a resource was created.
- 204 `No Content` - The request was successful but there is no representation to return (that is, the response is empty).
- 400 `Bad Request` - The request could not be understood or was missing required parameters.
- 401 `Unauthorized` - Authentication failed or user does not have permissions for the requested operation.
- 403 `Forbidden` - Access denied.
- 404 `Not Found` - Resource was not found.
- 405 `Method Not Allowed` - Requested method is not supported for the specified resource.
- 429 `Too Many Requests` - Exceeded API limits. Pause requests, wait one minute, and try again.
- 503 `Service Unavailable` - The service is temporary unavailable. Try again later.

# Group Pages

## Pages [/api/v1/pages?fields={pole}]
Vraceni stranek pro menu layoutu.
### Pages [GET]
+ Response 200

        [
            {"name": "O nás", "url": "o-nas"},
            {"name": "Obchodní podmínky", "url": "obchodni-podminky"},
            {"name": "FAQ", "url": "faq"},
            {"name": "Kontakt", "url": "kontakt"}
        ]

## Page detail [/api/v1/pages?url={url}]
Vraceni detailu stranky.
### Page detail [GET]
+ Response 200

        {
            "name": "O nás",
            "text": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit."
        }
        
# Group Kategory

## List all Kategory [/api/v1/categories]
Seznam všech kategorií.
### List [GET]
+ Response 200

        [
            {"id": 123, "name": "Android", "url": "android"},
            {"id": 234, "name": "iPhone", "url": "iphone"},
            {"id": 334, "name": "BlackBerry", "url": "blackberry"},
            {"id": 434, "name": "Symbian", "url": "symbian"},
            {"id": 534, "name": "Windows Phone", "url": "windows-phone"},
            {"id": 634, "name": "Levné", "url": "levne"},
            {"id": 734, "name": "Příslušenství", "url": "prislusenstvi", "children": [
                {"id": 834, "name": "Baterie", "url": "baterie"},
                {"id": 934, "name": "Držáky", "url": "drzaky"},
                {"id": 144, "name": "Nabíječky", "url": "nabijecky"},
                {"id": 894, "name": "Pouzdra", "url": "pouzdra"}
            ]}
        ]



## Create Kategory [/api/v1/categories ]
Vytvoření nového kategorie.
### Create Kategory [POST]
+ Response  201 

    + Header
            
            Access-Control-Allow-Origin: *
            
    + Body
        
            {
                "id": 999
            }

## Detail [/api/v1/categories?url={url}]
Detail kategorie podle URL.
### [GET]
+ Response 200

        {
            "name": "iPhone",
            "url": "iphone",
            "children": [],
            "minPrice": 1000,
            "maxPrice": 23000,
            "params": [
                {
                    "name": "Funkce",
                    "code": "funkce",
                    "values": [
                        {"code": "wifi", "value": "WiFi"},
                        {"code": "bluetooth", "value": "BlueTooth"},
                        {"code": "dual-sim", "value": "Dual SIM"},
                        {"code": "gps", "value": "GPS"},
                        {"code": "fm-radio", "value": "FM radio"}
                    ]
                },
                {
                    "name": "Operační paměť",
                    "code": "operacni-pamet",
                    "values": [
                        {"code": "256", "value": "256 MB"},
                        {"code": "512", "value": "512 MB"},
                        {"code": "1024", "value": "1024 MB"},
                        {"code": "2048", "value": "2048 MB"},
                        {"code": "4096", "value": "4096 MB"}
                    ]
                 },
                 {
                    "name": "Uložiště",
                    "code": "uloziste",
                    "values": [
                        {"code": "0-2", "value": "0-2 GB"},
                        {"code": "2-10", "value": "2-10 GB"},
                        {"code": "10-50", "value": "10-50 GB"},
                        {"code": "50-100", "value": "50-100 GB"},
                        {"code": "100-512", "value": "100-512 GB"}
                    ]
                },
                {
                    "name": "Paměťová karta",
                    "code": "pametova-karta",
                    "values": [
                        {"code": "sdhc", "value": "SDHC"},
                        {"code": "micro-sd", "value": "Micro SD"},
                        {"code": "micro-sdxc", "value": "Micro SDXC"},
                        {"code": "sdxc", "value": "SDXC"},
                        {"code": "micro-sdhc", "value": "Micro SDHC"}
                    ]
                }
            ]
        }
        
## Edit Kategory [/api/v1/categories/{id}]
Editace kategorie s id {id} 
### Edit [PUT]
+ Response 204

### Delete Kategory [DELETE]
+ Response 204


# Group Users
## List all Users [/api/v1/users]
Seznam všech správců.
### List [GET]
+ Response 200

        [
            {"id": 123, "name": "Petr", "email": "palicka.stanislav@seznam.cz"},
            {"id": 234, "name": "Kuba", "email": "palicka.stanislav@test.com"},
            {"id": 345, "name": "Superman", "email": "superman@test.cz"}
        ]

### Create User [POST]
+ Response 201

        {
            "id": 789
        }
        
## Detail User [/api/v1/users/{id}]
Vrací kompletní informace o spravci s ID {id}.
### Detail [GET]
+ Response 200

        {
            "id": 12345,
            "name": "Stanislav Palička",
            "email": "palicka.stanislav@gmail.com"
        }
        
### Edit User [PUT]
+ Response 204

### Delete User [DELETE]
+ Response 204

## authToken [/api/v1/users/0]
Vraceni authTokenu pro daneho uzivatele
### authToken [POST]
+ Response 200

        {
            "authToken": "d8dd64d0m5sjkd64dkzs876dk"
        }
        

# Group Orders
## List all Orders [/api/v1/orders?filter={filter}&limit={limit}&offset={offset}&order={order}&query={query}]
Výběr všech objednávek z databáze.
### Orders [GET]
+ Response 200

        {"count":50,
        "orders":[
        {"number": 123456789,
        "date": "2013-01-30T13:27:00Z",
        "customer":{"name": "Stanislav", "surname": "Palička", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
        "status": {"code": "pending", "name": "Zpracovává se"},
        "products": [
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
        ],
        "transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
        "price": 45000},
        {"number": 123456789,
        "date": "2013-01-30T13:27:00Z",
        "customer":{"name": "Stanislav", "surname": "Palička", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
        "status": {"code": "completed", "name": "Dokončeno"},
        "products": [
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
        ],
        "transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
        "price": 45000},
        {"number": 123456789,
        "date": "2013-01-30T13:27:00Z",
        "customer":{"name": "Stanislav", "surname": "Palička", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
        "status": {"code": "completed", "name": "Dokončeno"},
        "products": [
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
        ],
        "transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
        "price": 45000},
        {"number": 123456789,
        "date": "2013-01-30T13:27:00Z",
        "customer":{"name": "Stanislav", "surname": "Palička", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
        "status": {"code": "cancelled", "name": "Zrušeno"},
        "products": [
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
        ],
        "transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
        "price": 45000},
        {"number": 123456789,
        "date": "2013-01-30T13:27:00Z",
        "customer":{"name": "Stanislav", "surname": "Palička", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
        "status": {"code": "completed", "name": "Dokončeno"},
        "products": [
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
        ],
        "transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
        "price": 45000}
        ]}

## Create Order [/api/v1/orders]
### Vložení nové objednávky do databáze. [POST]
+ Response 200
            
            {"number": "1234567"}

## Edit Order [/api/v1/orders/{number}]
### Částečná editace jedné objednávky (např. editace statusu). [POST]
+ Response 204 (application/json)

### Editace objednavky v databazi. [PUT]
+ Response 204

### Detail Order [GET]
+ Response 200

        {"number": 123456789,
        "date": "2013-01-30T13:27:00Z",
        "customer":{"name": "Stanislav", "surname": "Palička", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín", "email": "palicka.stanislav@seznam.cz"},
        "status": {"code": "completed", "name": "Dokončeno"},
        "products": [
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
          {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
        ],
        "transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
        "price": 45000}

